model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 3
  latent_dim: 64

data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.94
  kld_weight: 0.0003
  manual_seed: 100

trainer_params:
  accelerator: gpu
  devices: 1
  max_epochs: 200
  gradient_clip_val: 1.5

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"